spring:
  application:
    name: demo

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
    port: ${MAIL_PORT}
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

jwt:
  access-token-key: ${ACCESS_TOKEN_KEY}
  access-token-expires: 900000
  refresh-token-expires: 1209600000

lunch-api:
  key: ${MEAL_API_KEY}

