name: Java CI with Gradle

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build
      
    - name: Notify Discord
      if: success()
      uses: discord-actions/message@v2
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
        message: "Success Gradle Build"
        
    - name: Notify Discord
      if: failure()
      uses: discord-actions/message@v2
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
        message: "Failed to Gradle Build"

  